/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#333a45",
        "inverse-on-surface": "#2a313c",
        "on-secondary": "#003825",
        "on-tertiary-container": "#00422c",
        "surface-container-highest": "#2e3540",
        "primary-fixed": "#6ffbbe",
        "error": "#ffb4ab",
        "outline-variant": "#3c4a42",
        "surface-container-high": "#232a35",
        "surface": "#0d141e",
        "on-primary-fixed-variant": "#005236",
        "on-primary-fixed": "#002113",
        "on-background": "#dce3f1",
        "primary-fixed-dim": "#4edea3",
        "secondary-container": "#00bd85",
        "secondary": "#45dfa4",
        "surface-dim": "#0d141e",
        "surface-container-low": "#151c26",
        "tertiary-fixed": "#85f8c4",
        "surface-container-lowest": "#080f18",
        "background": "#0d141e",
        "primary-container": "#10b981",
        "on-surface-variant": "#bbcabf",
        "on-tertiary-fixed": "#002114",
        "on-error": "#690005",
        "secondary-fixed": "#68fcbf",
        "on-surface": "#dce3f1",
        "primary": "#4edea3",
        "tertiary-container": "#3eb686",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#45dfa4",
        "error-container": "#93000a",
        "outline": "#86948a",
        "tertiary": "#68dba9",
        "on-primary-container": "#00422b",
        "surface-container": "#19202a",
        "on-tertiary": "#003825",
        "surface-tint": "#4edea3",
        "surface-variant": "#2e3540",
        "on-secondary-container": "#00452e",
        "on-primary": "#003824",
        "on-secondary-fixed-variant": "#005137",
        "tertiary-fixed-dim": "#68dba9",
        "inverse-primary": "#006c49",
        "inverse-surface": "#dce3f1",
        "on-secondary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#005137"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "display-lg": ["Inter"],
        "code-sm": ["JetBrains Mono"]
      }
    },
  },
  plugins: [],
};
