/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#333a45",
        "inverse-on-surface": "#2a313c",
        "on-secondary": "#003825",
        "on-tertiary-container": "#00422c",
        "surface-container-highest": "#2e3540",
        "primary-fixed": "#93C5FD",
        "error": "#EF4444",
        "outline-variant": "#1E293B",
        "surface-container-high": "#151E2E",
        "surface": "#080D16",
        "on-primary-fixed-variant": "#005236",
        "on-primary-fixed": "#002113",
        "on-background": "#E5E7EB",
        "primary-fixed-dim": "#60A5FA",
        "secondary-container": "#2563EB",
        "secondary": "#60A5FA",
        "surface-dim": "#080D16",
        "surface-container-low": "#111827",
        "tertiary-fixed": "#67E8F9",
        "surface-container-lowest": "#080D16",
        "background": "#080D16",
        "primary-container": "#3B82F6",
        "on-surface-variant": "#94A3B8",
        "on-tertiary-fixed": "#002114",
        "on-error": "#690005",
        "secondary-fixed": "#93C5FD",
        "on-surface": "#E5E7EB",
        "primary": "#3B82F6",
        "tertiary-container": "#22D3EE",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#45dfa4",
        "error-container": "#93000a",
        "outline": "#86948a",
        "tertiary": "#68dba9",
        "on-primary-container": "#00422b",
        "surface-container": "#111827",
        "on-tertiary": "#003825",
        "surface-tint": "#3B82F6",
        "surface-variant": "#1E293B",
        "on-secondary-container": "#00452e",
        "on-primary": "#003824",
        "on-secondary-fixed-variant": "#005137",
        "tertiary-fixed-dim": "#68dba9",
        "inverse-primary": "#006c49",
        "inverse-surface": "#dce3f1",
        "on-secondary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#005137"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "display-lg": ["Inter"],
        "code-sm": ["JetBrains Mono"]
      }
    },
  },
  plugins: [],
};
